Ignore 'phantom stdout' errors
Some sites which contain javascript errors cause pa11y to outline extra lines such as:
```
phantom stdout: TypeError: 'undefined' is not a function (evaluating 'WDN.jQuery(document)')
```

So, running `json_decode` on the entire output was failing, causing the metric to be marked as 'incomplete'.  Instead, search the output for a line that can pass json_decode